#!/usr/bin/env ruby
lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'rubygems'
require 'dupler'

begin
  Dupler::Cli.start
rescue Dupler::DuplerException => ex
  $stderr.puts ex.message
  exit 1
end