#!/usr/bin/env ruby
# frozen_string_literal: true

lib = File.expand_path("../lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "rubygems"
require "dupler"

begin
  Dupler::Cli.start
rescue Dupler::DuplerException => e
  warn e.message
  exit 1
end
